### ISSUE TITLE
RFC: Long running features

### ISSUE THREAD

**Issue by digitalsadhu** [mediasuitenz/tech-stack#19]
## Description

This issue is to discuss a general approach to handling features that are either long running or perhaps have several people working on them at the same time.
## Concerns
- We don't want incomplete features going onto develop (or at least being visible to the client)
- We don't want code getting way behind develop and costing us major time in rebasing
- We want to avoid pain caused when multiple people work together on different parts of a feature
## Possible approaches

**When a single person needs to work on a longer running feature:**
- use a single branch off develop
- caveat: don't want branches to be outstanding for a long period of time
- so: feature flags may be appropriate in some cases

**When multiple people need to work on the same feature:**
- prefer working closely, consider working on the same branch if possible and crossing over, even pairing.
- if necessary, can use feature branches (multiple people PR onto feature branch) where branches don't make sense to go onto develop on their own
- caveat: don't want feature branches to be outstanding for a long period of time
- so: feature flags may be appropriate in some cases
## Testing implications
- If feature branch exists, Tester to test main feature branch rather than individual PRs onto that feature branch to avoid duplicated effort

@mediasuitenz/developers

**Comment by JonForest** [comment]
I'm a fairly big fan of having a feature branch with sub-branches, and then keeping all these up-to-date regularly.  
Should merge from develop, through feature branch to sub-branch.  Recommend merge over rebase in these circumstances as otherwise it seems you end up fixing the same conflicts time after time.

Not a big fan of feature flags, as having conditionals throughout the code base makes it much harder to understand, and offers another area you can introduce errors.

**Comment by anotheredward** [comment]
Sub-branch are winner.
