### ISSUE TITLE
RFC: Loopback pros/cons

### ISSUE THREAD

**Issue by markstuart** [mediasuitenz/tech-stack#8]
# To Loopback or not to Loopback?

Hey team, there has been a bit of discussion around pain points in Loopback, and the possibility of replacing the server side framework.

In order to gain an understanding of whether it is worth investigating any further, we'd like some feedback from the team on Loopback.

We have already moved away from the Loopback `autoUpdate/autoMigrate` ideas in favour of `knex` and more strict migration strategies in a couple of projects, so one way of solving some pain points could be to bring in other libraries where needed. Though it may be difficult to achieve in some cases, depending on where the pain is.

Please comment on this issue in a format similar to this:
## Pros:
1. Thing that Loopback (or the ecosystem) does well
2. ...
3. ... as many as you like
## Cons:
1. Thing that Loopback or it's ecosystem does not do well
2. ...
3. ...
## General Comments:

Something about the more general idea of replacing Loopback, cost of change, personal opinions on whether or not it's worth changing or even investigating changing. Or just anything else you want to say that's on topic.

**Comment by matt-in-a-hat** [comment]
Does it have any easily integrated CMS available? I guess that's a con, and why we've used SilverStripe in a couple of places instead.

**Comment by anotheredward** [comment]
## First draft, will think over and refine

Pros:
* We know it now, and it's in a number of our existing projects
* Establishes patterns around writing a larger express app
* Has most of what we need (need a list here)
* We now have example code for most activities
* Having a standard endpoint structure and JSONAPI adapter is pretty sweet
* It's introducing promises!

Cons:
* Hooks make an easy thing (reading/writing data) easier, but make more difficult things harder than an MVC approach or middleware/route approaches.
* It's bad at sql (eg: no foreign keys, add more here)
* Two ways of doing everything (code and in JSON)
* JSON configuration is not explorable, easy to get wrong, produces obscure error messages, and requires reading the documentation
* Documentation is always slightly out of date (Though it's gotten a lot better)
* Parameter Types seems to weak at the endpoint level, so we need to fix with validation checks, eg: id being "Number" when it's actually "Integer > 0"
* Permission system is a bit crazy, especially the race between competing permissions
* Very permissive by default (fields need whitelisting, then endpoints need disabling, then roles need defining to further lock down endpoints/fields)
* It's not MVC, which some of us we're reasonably used to (eg: PHP's Yii)

Things I don't know:
* I haven't worked out how to drop down to SQL when necessary, because there are some times it's seriously necessary

I also feel that a lot of my unhappiness has been learning/surprises/not having standard ways of doing things.

I also feel that some of the cons can be addressed and avoided in future.

My current opinion is that it's better/easier than using something else that we don't know, BUT
we should use the appropriate tool for the appropriate project.
In terms of scaling they go like this to me:
* Only html/css/jquery
* Only a backend server with express/knex
* html/css/jquery + express/knex server
* ember app + loopback

**Comment by digitalsadhu** [comment]
@matt-in-a-hat A large reason for silverstripe is those govt type peeps and their policy type stuff I believe. There are a few node CMSs around, not integrate with loopback.

**Comment by matt-in-a-hat** [comment]
I think cruise guide and leapfrog(?) used SS for lack of known other cms

**Comment by digitalsadhu** [comment]
## Things we get from loopback
- ORM
  - expressive query dsl both through URLs and when using the node API
  - bunch of databases supported (who cares, we only use postgres)
  - various types of relationships supported
  - multiple databases at the same time
- CRUD
  - built in remote methods that wire together the ORM layer to routes
- validation
  - kinda crap but its there
- Authentication
  - token or cookie based, pretty much out of the box
- Authorization
  - ACLS on models with ability to write custom role resolvers. In reality this tends to only go so far and you tend to write a lot of custom stuff
- endpoint explorer
  - kinda handy to have but by no means a deal breaker in IMO
- JSON API 
  - not a feature of loopback as such but not available for anything else in node land
- ordered middleware
  - middleware can be assigned and grouped into phases
- user signup/login flow
  - various bits of functionality on the user object for things like password reset, login, logout
- mixins
- boot scripts
- components

### The highest value items in there in my mind are:
- ORM (mostly due to the query DSL at the URL level)
- JSON API - theres not much else out there for other projects 
- user signup/login flow - handy

### Reasons why the rest isn't so high value
- CRUD - you can standardise an express CRUD setup pretty easily (few hundred lines) and then use it across projects
- validation - there are better validation libraries out there (eg. joi from the hapi project)
- auth and auth - the ACLs and role resolver are pretty nice when they provide what you need. Seems like most of the time you need to write a lot yourself
- endpoint explorer - a nice to have, not a deal breaker. Use PAW
- ordered middleware - yuck, this whole concept doesn't really work for me.
- mixins - its javascript, just mix stuff in 
- boot scripts - meh
- components - nice but super easy to do yourself 

## A few pros and cons

### Pros 

- Can be quite productive
- Easy to endpoint test
- provided CRUD means there are many cases where you don't need to write code = less code to maintain
- pretty nice ORM with relations, side loading and query dsl 

### Cons
- no migration story
- not so great validations
- really terrible apis (in places, other places are great see above)
- hideous hard to grok source code 
- project seems to lack clear direction and good vision (follows what whoever wants to get in there a bit much)
- operation hooks are utterly terrible 
- connectors don't support 
  A. Any postgis 
  B. Custom types (can't make use of jsonb for example in postgres)
- pretty crappy docs (average at best)

## Some thoughts on how to replace loopback

I have thought quite a bit about this in the past and I think i'd probably go with 
express and replace other loopback features on a case by case basis.
JSON API serialization could be added to bookself without too much trouble, the rest 
of the JSON API stuff we get from loopback-component-jsonapi would require a bit 
of work.

### Potential replacements

- ORM - bookshelf
- CRUD - write and codify a set of express CRUD routes
- validation - joi
- Authentication - express middleware, custom code, codify patterns
- Authorization - express middleware, custom code, codify patterns
- endpoint explorer - don't bother
- JSON API - adapt and expand on loopback-jsonapi-model-serializer
- ordered middleware - don't bother
- user signup/login flow - custom code, find and codify patterns
- mixins - unneeded, just mixin objects into objects
- boot scripts - only really makes sense in the loopback context
- components - only really makes sense in the loopback context

additionally
- express for the main framework
- knex for seeds and migrations 
- decide on and codify other aspects such as project/folder structure
- could maintain a project scaffolder such as yeoman or perhaps better still ember cli

**Comment by JonForest** [comment]
Loopback's backing by IBM has to be a point in it's favour.  You'd hope, and expect so from recent history, that IBM will stick by this in the long term and we're not going to get too hit when the crowd move on to the next new 'shiny' framework.

As much as I like the Express idea, I fear creating our own backend custom stack.  Express wins because it's the whole shooting match, and there is a huge body of knowledge and community surrounding.  While Loopback may not be perfect, if we create our own custom stack, we're the only ones we can turn to with problems.

**Comment by ewen** [comment]
Sorry @markstuart no pros/cons list :)

### Auto-generating APIs
I personally am not a fan of the default API creation, it makes it easy to accidentally leave unsecured endpoints and in my (very limited) experience the CRUD is nearly never sufficient without modifying the model anyway with hooks. I'd prefer to add endpoints as I want them.

The explorer is useful and a great tool to help with development. Only complaint is that's incredibly slow to set up routing for which slows down development (adds ~20s to a server restart in the Water project). So we now have it disabled anyway.

### Documentation
The documentation leaves a fair amount to be desired e.g. undocumented core features like `getAsync`. In general what is there isn't too bad just lacking detail, I guess it's just a big framework and the docs are spread too thin.

I've found the code examples useful.

### Code quality
A few people have commented that the loopback code is a bit of a mess, personally I haven't really found this *BUT* I've only delved a couple of times into the Model code so wouldn't give this much weight.

### Migrations / Fixtures
The Loopback migrations are pretty bad from what I've seen - at least switching out to Knex was painless.

Fixturing is also very slow and lacks basic features like [bulk inserts|https://github.com/strongloop/loopback/issues/1275]. Switching to Knex took our fixturing time from ~50s to about 2s.

### Security
Loopback has a lot of security functionality built in but the ACLs are confusing and hard to get right. From what I've seen it's probably easier to just skip ACLs and implement the auth logic in the models (along with whitelisting endpoints for the model).

### JSON API and working with Ember
This is pretty sweet on the whole, I ran into a lot of trouble with including related models and getting them to format properly so that Ember can load them in a big chunk. I believe Richie's work on `loopback-jsonapi-model-serializer` would fix these but haven't yet tried it out.

### Conclusion
On the whole I don't mind Loopback too much but sometimes wonder how much value it's providing. I find it a bit clunky and occasionally run into what I would consider small tasks taking a long time. I think you kind of build up a cookbook of ways to do things in it over time which helps with the productivity.

**Comment by ebuckley** [comment]
The discussion here is awesome, really great read.

One aspect of loopback that hasn't been mentioned, is how fast it is to stand up a REST api against a standard relational database. In the Water-Allocation project, our initial work was just about mapping to the existing DB, we basically only had to use the loopback configuration DSL for the first couple iterations. This enabled us to show a lot of movement on the client side, this gives a pretty compelling demo and keeps clients happy.

In terms of really big "web scale" systems, I think loopback plays a part, but I'm not convinced it is the best option for the interface between a browser and the server.  The Model/View thing doesn't really scale well forever, something like [graphql (10 min read)](https://facebook.github.io/react/blog/2015/05/01/graphql-introduction.html) could be a better option if we are developing a product of that scale.

For projects in the 8-12 week scope, loopback seems like a really great fit.

For micro-services, loopback can be a great way to expose an API interface to a database. This is very relevant for upcoming MDC work.

**Comment by anotheredward** [comment]
That reminds me. I've been thinking for a little while now that we need to discuss: "Using the right tool for the job", and clearly defining which tools for what jobs. Would that be worth an issue?

**Comment by pnw** [comment]
More to come I guess

## Pros
* Easy up and running
* Code by configuration (see cons section) gives some cool features like an auto-generated api explorer

## Cons
* Lots of features built for specific use cases that are not generally useful, e.g. validation not allowing null values, scoping is finicky at best and requires stupid hacks to really do anything useful
* Code by static configuration: JSON config files galore! JSON is probably one of the worst configuration file formats. Yes, it forces you to keep things simple, but in practice ends up obfuscating things. This is especially true when you invariably have to use alternate configuration methods (e.g. adding constraints in the model.js file), which results in a single thing being configured in multiple places at once
* ORM is really basic, especially since a lot of our domain-specific work ends up requiring some gnarly sql - it also does not allow you to drop down to raw sql very easily, as they expect everything should be done through their MongoDB AF api.

**Comment by JonForest** [comment]
The big Pro of Loopback at this stage is lack of alternatives I think.  I'd love us to write our own, but I don't think we have that luxury.
Without subscribing to the sunk-cost fallacy, we've invested a lot of time in learning it's quirks and I'm not sure we'd see any benefits of a move within six to eight months.

**Comment by anotheredward** [comment]
I'm on the same page here @JonForest , but I also think naming components that don't work and slowly replacing them with components that do is also sensible. eg: validation

**Comment by anotheredward** [comment]
Conclusion: Moving away from Loopback and trying alternatives.
